spring.application.name=thymeleaf

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update

# MySQL DataSource Configuration
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
